package com.hhi.sap.table.term

class TERM_MONTH {
  val DATABASE = "sap"
  val TABLE11 = s"$DATABASE.thd_mrpl_month"
  val TABLE12 = s"$DATABASE.thd_weight_month"
  val TABLE13 = s"$DATABASE.thd_amount_month"

  val COMPANYID = "companyid"
  val SAUPBU = "saupbu"
  val PSPID = "pspid"
  val SERNO = "serno"
  val STG_GUBUN = "stg_gubun"
  val MAT_GUBUN = "mat_gubun"
  val WCM2 = "wcm2"
  val WCM1 = "wcm1"
  val WC = "wc"
  val WCP1 = "wcp1"
  val WCP2 = "wcp2"
  val WCP3 = "wcp3"
  val WCP4 = "wcp4"
  val WCP5 = "wcp5"
  val WCP6 = "wcp6"
  val WCP7 = "wcp7"
  val WCP8 = "wcp8"
  val WCP9 = "wcp9"
  val WCP10 = "wcp10"
  val PGMID = "pgmid"
  val CNAM = "cnam"
  val CDAT = "cdat"
  val CTIM = "ctim"
}