package com.hhi.sap.table.term

class TERM_THD_MRPL_WEEK {
  val DATABASE = "sap"
  val TABLE = s"$DATABASE.thd_mrpl_week"

  val COMPANYID = "companyid"
  val SAUPBU = "saupbu"
  val PSPID = "pspid"
  val SERNO = "serno"
  val STG_GUBUN = "stg_gubun"
  val MAT_GUBUN = "mat_gubun"
  val WCM5 = "wcm5"
  val WCM4 = "wcm4"
  val WCM3 = "wcm3"
  val WCM2 = "wcm2"
  val WCM1 = "wcm1"
  val WC = "wc"
  val WCP1 = "wcp1"
  val WCP2 = "wcp2"
  val WCP3 = "wcp3"
  val WCP4 = "wcp4"
  val WCP5 = "wcp5"
  val WCP6 = "wcp6"
  val WCP7 = "wcp7"
  val WCP8 = "wcp8"
  val WCP9 = "wcp9"
  val WCP10 = "wcp10"
  val WCP11 = "wcp11"
  val WCP12 = "wcp12"
  val WCP13 = "wcp13"
  val WCP14 = "wcp14"
  val WCP15 = "wcp15"
  val WCP16 = "wcp16"
  val WCP17 = "wcp17"
  val WCP18 = "wcp18"
  val WCP19 = "wcp19"
  val WCP20 = "wcp20"
  val WCP21 = "wcp21"
  val WCP22 = "wcp22"
  val WCP23 = "wcp23"
  val WCP24 = "wcp24"
  val WCP25 = "wcp25"
  val PGMID = "pgmid"
  val CNAM = "cnam"
  val CDAT = "cdat"
  val CTIM = "ctim"
}