package com.hhi.sap.table.term

class TERM_ZPDCT6123 {
  val DATABASE = "sap".toUpperCase()
  val TABLE = s"$DATABASE.thd_zpdct6123".toUpperCase()

  val COMPANYID = "companyid".toUpperCase()
  val SAUPBU = "saupbu".toUpperCase()
  val MATNR = "matnr".toUpperCase()
  val POSNR = "posnr".toUpperCase()
  val IDNRK = "idnrk".toUpperCase()
  val ZINOUT = "zinout".toUpperCase()
  val PSPID = "pspid".toUpperCase()
  val ZMRPL = "zmrpl".toUpperCase()
  val ZKGPORNO = "zkgporno".toUpperCase()
  val ZKGBNFPO = "zkgbnfpo".toUpperCase()
  val ZMIDACTNO = "zmidactno".toUpperCase()
  val BANFN = "banfn".toUpperCase()
  val BFNPO = "bfnpo".toUpperCase()
  val ZHDRMATNR = "zhdrmatnr".toUpperCase()
  val ZEXDATE = "zexdate".toUpperCase()
  val MENGE = "menge".toUpperCase()
  val ISSQTY = "issqty".toUpperCase()
  val MEINS = "meins".toUpperCase()
  val ZKGVNDCOD = "zkgvndcod".toUpperCase()
  val ZBLKNO = "zblkno".toUpperCase()
  val WERKS = "werks".toUpperCase()
  val ZFROMSYS = "zfromsys".toUpperCase()
  val ZPTMR = "zptmr".toUpperCase()
  val WEEK = "week".toUpperCase()
  val MONTH = "month".toUpperCase()
  val STG_GUBUN = "stg_gubun".toUpperCase()
  val MAT_GUBUN = "mat_gubun".toUpperCase()
  val PGMID = "pgmid".toUpperCase()
  val CNAM = "cnam".toUpperCase()
  val CDAT = "cdat".toUpperCase()
  val CTIM = "ctim".toUpperCase()
}