package com.hhi.sap.table.term

class TERM_ZPDCT6023 {
  val DATABASE = "sap".toUpperCase()
  val TABLENAME = "thd_zpdct6023".toUpperCase
  val TABLE = s"$DATABASE.$TABLENAME".toUpperCase()

  val COMPANYID = "companyid".toUpperCase()
  val SAUPBU = "saupbu".toUpperCase()
  val ZTRKNO = "ztrkno".toUpperCase()
  val ZREVNO = "zrevno".toUpperCase()
  val MATNR = "matnr".toUpperCase()
  val POSNR = "posnr".toUpperCase()
  val IDNRK = "idnrk".toUpperCase()
  val ZINOUT = "zinout".toUpperCase()
  val PSPID = "pspid".toUpperCase()
  val ZIDWGNO = "zidwgno".toUpperCase()
  val ZMDWGNO = "zmdwgno".toUpperCase()
  val ZMIDACTNO = "zmidactno".toUpperCase()
  val MENGE = "menge".toUpperCase()
  val MEINS = "meins".toUpperCase()
  val BRGEW = "brgew".toUpperCase()
  val ZBLKNO = "zblkno".toUpperCase()
  val ZPCSNO = "zpcsno".toUpperCase()
  val ZKGPORNO = "zkgporno".toUpperCase()
  val ZKGBNFPO = "zkgbnfpo".toUpperCase()
  val ZHDRMATNR = "zhdrmatnr".toUpperCase()
  val BANFN = "banfn".toUpperCase()
  val BFNPO = "bfnpo".toUpperCase()
  val ZCNFDATE = "zcnfdate".toUpperCase()
  val ZFROMSYS = "zfromsys".toUpperCase()
  val ZPTMR = "zptmr".toUpperCase()
  val ZMRPL = "zmrpl".toUpperCase()
  val WERKS = "werks".toUpperCase()
  val WEEK = "week".toUpperCase()
  val MONTH = "month".toUpperCase()
  val STG_GUBUN = "stg_gubun".toUpperCase()
  val MAT_GUBUN = "mat_gubun".toUpperCase()
  val PGMID = "pgmid".toUpperCase()
  val CNAM = "cnam".toUpperCase()
  val CDAT = "cdat".toUpperCase()
  val CTIM = "ctim".toUpperCase()
}