package com.hhi.sap.table.term

class TERM_ZPSCT600 {
  val DATABASE = "sap".toUpperCase()
  val TABLE = s"$DATABASE.zpsct600".toUpperCase()

  val COMPANYID = "companyid".toUpperCase()
  val SAUPBU = "saupbu".toUpperCase()
  val PSPID = "pspid".toUpperCase()
  val SHIP_KIND = "ship_kind".toUpperCase()
  val SHIP_TYPE_1 = "ship_type_1".toUpperCase()
  val DOCK = "dock".toUpperCase()
  val BTYPE = "btype".toUpperCase()
  val DUR_AND = "dur_and".toUpperCase()
  val D1_ND = "d1_nd".toUpperCase()
  val D2_ND = "d2_nd".toUpperCase()
  val D3_ND = "d3_nd".toUpperCase()
  val DUR_QND = "dur_qnd".toUpperCase()
  val CNTR = "cntr".toUpperCase()
  val DWT_SC = "dwt_sc".toUpperCase()
  val WEIGT_PR = "weigt_pr".toUpperCase()
  val WEIGT_BB = "weigt_bb".toUpperCase()
  val WEIGT_LD = "weigt_ld".toUpperCase()
  val WC = "wc".toUpperCase()
  val KL = "kl".toUpperCase()
  val FT = "ft".toUpperCase()
  val LC = "lc".toUpperCase()
  val DL = "dl".toUpperCase()
  val PGMID = "pgmid".toUpperCase()
  val CNAM = "cnam".toUpperCase()
  val CDAT = "cdat".toUpperCase()
  val CTIM = "ctim".toUpperCase()
  val CO_STAT = "co_stat".toUpperCase()
}